spring:
  application:
    name: spring-ai-video-analysis-cookbook
  servlet:
    multipart:
      max-file-size: 50MB      # Allow larger video uploads
      max-request-size: 50MB   # Total request size limit

  # AI configurations
  ai:
    openai:
      api-key: ${GEMINI_API_KEY}
      base-url: https://generativelanguage.googleapis.com/v1beta/openai
      chat:
        completions-path: /chat/completions
        options:
          model: gemini-2.0-flash-exp

# (Optional) For detailed request/response logging
logging:
  level:
    org.zalando.logbook.Logbook: TRACE

